from pydantic import BaseModel
from typing import Optional
from datetime import datetime

# Institution model
class Institution(BaseModel):
    # id: Optional[int]  # Autogenerated, hence Optional for input
    name: str
    location: str
    created_at: Optional[datetime] = datetime.now()
